/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * infrastructure API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { OutboundSseEvent } from "./model";
import { customInstance } from "./mutator/custom-instance";

export const subscribe = (requestedBy: string) => {
  return customInstance<OutboundSseEvent[]>({
    url: `/api/oneToOne/matchmaking/lifecycle/${requestedBy}/stream`,
    method: "GET",
  });
};

export const cancelMatchMaking = (requestedBy: string) => {
  return customInstance<void>({
    url: `/api/oneToOne/matchmaking/request/${requestedBy}/cancel`,
    method: "POST",
  });
};

export const findAStranger = (requestedBy: string) => {
  return customInstance<void>({
    url: `/api/oneToOne/matchmaking/request/${requestedBy}/findAStranger`,
    method: "POST",
  });
};

export const leaveMatchMaking = (requestedBy: string) => {
  return customInstance<void>({
    url: `/api/oneToOne/matchmaking/request/${requestedBy}/leave`,
    method: "POST",
  });
};

export type SubscribeResult = NonNullable<
  Awaited<ReturnType<typeof subscribe>>
>;
export type CancelMatchMakingResult = NonNullable<
  Awaited<ReturnType<typeof cancelMatchMaking>>
>;
export type FindAStrangerResult = NonNullable<
  Awaited<ReturnType<typeof findAStranger>>
>;
export type LeaveMatchMakingResult = NonNullable<
  Awaited<ReturnType<typeof leaveMatchMaking>>
>;
